### ISSUE TITLE
Order of annotations in the list is not always displayed correctly 

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#361]
When dragging annoations back and forth on the timeline the order of the annotations in the list is not always accurate (see screencast)
[Order not accurate.mp4.zip](https://github.com/opencast/annotation-tool/files/4291730/Order.not.accurate.mp4.zip)

**Comment by dagraf** [comment]
After a reload the order is right.

**Comment by JulianKniephoff** [comment]
This seems to have been fixed by the refactorings in #354.

**Comment by dagraf** [comment]
Bug still exists, see annotation 1 in screenshot./Users/DavidG/Desktop/Bildschirmfoto 2020-07-14 um 17.02.31.png

**Comment by dagraf** [comment]
Why did you move this bug to backlog?

**Comment by JulianKniephoff** [comment]
See https://github.com/opencast/annotation-tool/issues/358#issuecomment-677646093

**Comment by dagraf** [comment]
Works fine, thx!
